# Generated by Django 6.0.4 on 2026-04-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='created_at',
        ),
    ]
